.PHONY: clean All

All:
	@echo "----------Building project:[ Practica1_1 - Debug ]----------"
	@cd "Practica1_1" && "$(MAKE)" -f  "Practica1_1.mk"
clean:
	@echo "----------Cleaning project:[ Practica1_1 - Debug ]----------"
	@cd "Practica1_1" && "$(MAKE)" -f  "Practica1_1.mk" clean
